### ISSUE TITLE
Missing land cover types information for the Landsat NALCMS dataset

### ISSUE THREAD

**Issue by kasra-keshavarz** [kasra-keshavarz/datatool#10]
# problem statement
The landcover type information for the Landsat NALCMS dataset is missing, although there is a link that directs users to the main website of the dataset. This issue has been previously brought up by @wijayard for the `MODIS` dataset of this repository.

**Comment by ShervanGharari** [comment]
Hi Kasra, I there is a metadata with NALCMS [products](http://www.cec.org/north-american-environmental-atlas/land-cover-change-30m-2010-2015-landsat/). is that what you are after? this can be put in the same folder as where the data is. additionally the data explanation can be put into a csv file and added to the same folder as it makes easier to work with csv than a word doc.
BTW shouldn't this be under gistool?
tnx

**Comment by kasra-keshavarz** [comment]
Yes, I opened the issue under the wrong repository.
