### ISSUE TITLE
new dataset to be included

### ISSUE THREAD

**Issue by fuadyassin** [kasra-keshavarz/datatool#2]
Could you please add a data processor tool for the complementary historical data set for bias corrected CanRCM4? The data is stored here and please refer to the paper in HESSD for reference.  https://doi.org/10.5194/essd-12-629-2020
/project/6008034/Model_Output/181_WFDEI-GEM-CaPA_1979-2016

**Comment by fuadyassin** [comment]
Hi Sharvan, 
No urgency, it can wait in the queue. 
Thanks,
Fuad

**Comment by kasra-keshavarz** [comment]
Corrected with #4. Will be published in `v0.2.0` version. Sorry @fuadyassin for the delays.

**Comment by fuadyassin** [comment]
They are not part of the main file, or at least I don't use them. I guess Mohamed Elshamy processed/produced those two files for some purpose.
