### ISSUE TITLE
Adding a brief description of `datatool` for the `MESH` modelling community

### ISSUE THREAD

**Issue by kasra-keshavarz** [kasra-keshavarz/datatool#7]
# Issue description
The project could be briefly described for the `MESH` modelling community to communicate the features of the tool as suggested by [Ala Bahrami](https://github.com/AlaBahrami).

**Comment by ShervanGharari** [comment]
I think an example in MESH wiki by Ala would do the work(?) Feel free to introduce the tool @AlaBahrami

**Comment by AlaBahrami** [comment]
Totally agree @ShervanGharari and @kasra-keshavarz . It is nice to have the explanation of data-tool on MESH wiki page.

**Comment by kasra-keshavarz** [comment]
I noticed documentations are reflected on Usask's MESH Wiki, so I am closing this issue.
